# Generated by Django 5.1.3 on 2024-11-27 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('id_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.master', verbose_name='ID мастера')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.user', verbose_name='ID клиента')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='rem.user', verbose_name='ID клиента'),
        ),
    ]
