# Generated by Django 5.1.3 on 2024-11-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.user', verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
