# Generated by Django 5.1.3 on 2024-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0003_client_alter_master_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Рейтинг'),
        ),
    ]
