# Generated by Django 5.1.3 on 2024-11-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0004_remove_master_id_user_alter_master_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='username',
            field=models.CharField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Номер Заказа'),
            preserve_default=False,
        ),
    ]
