# Generated by Django 5.1.4 on 2024-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0007_historicalclient_historicalmaster_historicalorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='email',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='historicalmaster',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalmaster',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рейтинг'),
        ),
    ]
