# Generated by Django 5.1.3 on 2024-12-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0009_service_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='historicalclient',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='historicalmaster',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='username',
            new_name='full_name',
        ),
    ]
